before_install:
- openssl aes-256-cbc -K $encrypted_7e2bed8d5997_key -iv $encrypted_7e2bed8d5997_iv
  -in maps-agenda-test-faff9f1eab84.json.enc -out maps-agenda-test-faff9f1eab84.json
  -d
language: java
script:
- cd ..
- wget https://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.38.zip
- unzip appengine-java-sdk-1.9.38.zip >/dev/null
- cd maps-agenda/Maps\ Agenda
- ant build
- cd ..
deploy:
  provider: gae
  keyfile: maps-agenda-test-faff9f1eab84.json
  project: maps-agenda-test
  on: experimental
  config: Maps\ Agenda/war/WEB-INF/appengine-web.xml
